export const SET_REPORTS = 'SET_REPORTS';
export const REPORTS_IS_LOADING = 'REPORTS_IS_LOADING';

export const SET_REPORTS_BY_COUNTRIES = 'SET_REPORTS_BY_COUNTRIES';
export const REPORTS_BY_COUNTRIES_IS_LOADING = 'REPORTS_BY_COUNTRIES_IS_LOADING';

export const SET_DEATHS = 'SET_DEATHS';
export const DEATHS_IS_LOADING = 'DEATHS_IS_LOADING';

export const SET_TESTS_IN_US = 'SET_TESTS_IN_US';
export const TEST_IN_US_IS_LOADING = 'TEST_IN_US_IS_LOADING';

export const SET_CASES_AMERICA = 'SET_CASES_AMERICA';
export const CASES_AMERICA_IS_LOADING = 'CASES_AMERICA_IS_LOADING';